# Generated by Django 3.2 on 2024-07-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='輸入商店名稱', max_length=20)),
                ('address', models.CharField(max_length=50, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='上傳日期')),
            ],
        ),
    ]
