# Generated by Django 3.2 on 2024-07-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='introduction',
            field=models.CharField(default='無', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=models.CharField(default='無', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.CharField(default='無', max_length=200),
        ),
    ]
