# Generated by Django 3.2 on 2024-07-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_place_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='place',
            field=models.ForeignKey(help_text='商店名稱', null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.place'),
        ),
    ]
