# Generated by Django 3.2 on 2024-07-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_photo_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('Rstyle', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.place')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.tag')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(through='food.Tag_Management', to='food.Tag'),
        ),
    ]
