# Generated by Django 3.2 on 2024-07-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20240711_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Rstyle',
        ),
    ]
