# Generated by Django 3.2 on 2024-07-17 06:45

from django.db import migrations
import django_resized.forms
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20240711_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=-1, scale=None, size=[256, 256], upload_to='photos', validators=[food.models.validateFileSize]),
        ),
    ]
